version: "1.0.0"

volumes:
  mysql_data:
  mongo_data:
  mongo_config_data:

networks:
  command_database_net:
    name: "command_database_net"
  query_database_net:
    name: "query_database_net"

services:
  docker_mysql:
    container_name: "docker-mysql"
    image: mysql:8.0.32
    restart: unless-stopped
    volumes:
      - mysql_data:${MYSQL_VOLUMES}
    ports:
      - ${MYSQL_HOST_PORT}:${MYSQL_CONTAINER_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - command_database_net
    env_file:
      - .env
  docker_mongo:
    container_name: "docker-mongo"
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo_config_data:${MONGO_CONFIG_VOLUMES}
      - mongo_data:${MONGO_DATA_VOLUMES}
    ports:
      - ${MONGO_HOST_PORT}:${MONGO_CONTAINER_PORT}
    networks:
      - query_database_net
    env_file:
      - .env